name: Release

# 这个工作流会在你推送新标签时触发
on:
  push:
    tags:
      - 'v*'
# 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
env:
  GITHUB_TOKEN: ${{ secrets.CLASH_TOKEN  }}

jobs:
  build_and_release:
    name: Build and Release
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16' # 或你需要的任何版本

      - name: Install pnpm
        run: npm install -g pnpm

      # 接下来是你的其他步骤，比如安装依赖、构建等
      - name: Install dependencies
        run: npm install --no-frozen-lockfile

      # 设置 Rust 环境
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      # 安装 Tauri CLI
      - name: Install Tauri CLI
        run: cargo install tauri-cli --version ^1.0

      # 构建 Tauri 应用
      - name: Build App
        run: cargo tauri build

      # 创建 GitHub Release
      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            src-tauri/target/release/bundle/dmg/*.dmg

      # 完成后的输出
      - name: Check outputs
        run: echo "Release created with tag ${{ github.ref }}"
