name: Release

on:
  push:
    tags:
      - 'v*'
# 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
env:
  GITHUB_TOKEN: ${{ secrets.CLASH_TOKEN  }}

jobs:
  build_and_release:
    name: Build and Release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: npm install --no-frozen-lockfile

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Install Tauri CLI
        run: cargo install tauri-cli --version ^1.0

      - name: Build App
        run: cargo tauri build

      - name: Create GitHub Release
        if: matrix.os == 'macos-latest'
        uses: softprops/action-gh-release@v1
        with:
          files: |
            src-tauri/target/release/bundle/dmg/*.dmg
          token: ${{ secrets.CLASH_TOKEN }}

      - name: Create GitHub Release
        if: matrix.os == 'windows-latest'
        uses: softprops/action-gh-release@v1
        with:
          files: src-tauri/target/release/bundle/msi/*.msi
          token: ${{ secrets.CLASH_TOKEN }}

      - name: Check outputs
        run: echo "Release created with tag ${{ github.ref }}"
