name: Build and Release

on:
  push:
    branches:
      - main # 或者您想要侦听的任何其他分支

jobs:
  build:
    name: Build and Release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Install Tauri Dependencies
        run: |
          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            choco install nodejs-lts --version 14.17.0
            choco install python --version 3.9.0
          elif [ "${{ matrix.os }}" = "macos-latest" ]; then
            brew install node@14
            brew install python@3.9
          fi

      - name: Build
        run: |
          cargo install tauri-bundler --force
          cargo tauri build

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.os }}-artifacts
          path: src-tauri/target/release/bundle/*

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          path: release

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: release/*/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
